### PR TITLE
Fix a bug with a few raml files.

### PR DESCRIPTION
**Pull request by igoryurenko**
In case with a few raml files you had just one html file (generated from the last raml file) in the result.

### CODE REVIEW

**Comment by adrobisch** [comment]
Sorry for the delay, I was on vacation.

**Comment by igoryurenko** [comment]
Sorry to bother you again, but could you release a new artifact?

2016-08-01 22:16 GMT+03:00 Andreas Drobisch notifications@github.com:

**Comment by adrobisch** [comment]
No problem, thanks for the reminder. I will try to solve #13 and then create a new release. Will post an update here.

**Comment by adrobisch** [comment]
I just released 0.13. Thanks for the fix!

**Comment by igoryurenko** [comment]
It's my pleasure! :)
Thank you too for your quick response.

2016-08-10 23:53 GMT+03:00 Andreas Drobisch notifications@github.com:

**Pull request merged**
